### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Cloudinary' not found in /var/www/htdocs/.modman/cloudinary_magento/lib/CloudinaryExtension/CloudinaryImageProvider.php:114

### ISSUE THREAD

**Issue by andyt** [cloudinary/cloudinary_magento#45]
With version 2.9.6, installed via modman:

```Stack trace:
#0 /var/www/htdocs/.modman/cloudinary_magento/lib/CloudinaryExtension/CloudinaryImageProvider.php(34): CloudinaryExtension\CloudinaryImageProvider->authorise()
#1
/var/www/htdocs/.modman/cloudinary_magento/lib/CloudinaryExtension/CloudinaryImageProvider.php(42): CloudinaryExtension\CloudinaryImageProvider->__construct(Object(Cloudinary_Cloudinary_Model_Configuration), Object(CloudinaryExtension\ConfigurationBuilder), Object(CloudinaryExtension\UploadResponseValidator))
#2 /var/www/htdocs/.modman/cloudinary_magento/app/code/community/Cloudinary/Cloudinary/Model/Catalog/Product/Media/Config.php(30): CloudinaryExtension\CloudinaryImageProvider::fromConfiguration(Object(Cloudinary_Cloudinary_Model_Configuration))
#3 /var/www/htdocs/app/code/core/Mage/Core/Model/Config.php(1357): Cloudinary_Cloudinary_Model_Catalog_Product_Media_Config->__construct(Array)
# in /var/www/htdocs/.modman/cloudinary_magento/lib/CloudinaryExtension/CloudinaryImageProvider.php on line 114
```

**Comment by idobarnoam** [comment]
Thanks for letting us know @andyt Could you share the exact steps you took to install the module?

**Comment by idobarnoam** [comment]
Hey, @andyt I'm closing this issue since the PR above handles it.

Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues. the PR above handles it
